config:
  send_anonymous_usage_stats: False
  use_colors: True
  partial_parse: True


dbt_gsmk_postgres:
  outputs:
    dev:
      type: postgres
      threads: 3
      host: 192.168.1.50
      port: 5432
      user: postgres
      pass: "postgres"
      dbname: gsmk
      schema: dbt
  target: dev
